#!/usr/bin/env node

/*
 *********************************************************************************
 *                     Copyright (C) 2018 wystan
 *
 *       filename: ws-server.js
 *    description:
 *        created: 2018-06-28 23:23:48
 *         author: wystan
 *
 *********************************************************************************
 */

const SERVER_PORT = 8080;

var logi = (...args) => console.info('I|' + new Date().toISOString(), ...args);
var logw = (...args) => console.warn('W|' + new Date().toISOString(), ...args);
var loge = (...args) => console.error('E|' + new Date().toISOString(), ...args);
var logd = (...args) => console.log('D|' + new Date().toISOString(), ...args);

var express = require('express');
var app = express();
var expressWs = require('express-ws')(app);

app.use(express.static('static'));

app.ws('/app/v1.0.0', function(ws, req) {
    logi("=> new client");
    ws.on('close', ()=>{
        logi("=> closed");
    });
    ws.on('message', function(msg) {
        logi("get msg: ", msg);
    });
});

app.listen(SERVER_PORT);
logi("listen on", SERVER_PORT);

/************************************* END **************************************/